### ISSUE TITLE
Build Fail on Jetson Nano

### ISSUE THREAD

**Issue by tpoisonooo** [google/uVkCompute#15]
I try to build it on Jetson nano and encountered 2 errors:

## `glslc` not found
* [lunarg Vulkan SDK](https://vulkan.lunarg.com/) only provide x86_64 version
* glslang repo only provide `glslangValidator` and `spriv-xxx`

Is there any possible to build/install an arm`glslc` ?

## absl error
```bash
uVkCompute/uvkc/vulkan/dynamic_symbols.cc:179:10: error: could not convert ‘syms’ from ‘std::unique_ptr<uvkc::vulkan::DynamicSymbols>’ to ‘absl::lts_20211102::StatusOr<std::unique_ptr<uvkc::vulkan::DynamicSymbols> >’
   return syms;
```

I have checked https://github.com/google/uVkCompute/issues/14 and fixed it with `cmake -DCMAKE_C_COMPILER=$(which clang) -DCMAKE_CXX_COMPILER=$(which clang++) ..`. If uVkCompute only support clang, would you please review this PR https://github.com/google/uVkCompute/pull/16  ?

**Comment by tpoisonooo** [comment]
Ah,  https://github.com/google/shaderc involves `glslc`~

**Comment by tpoisonooo** [comment]
Ah,  the owner  of `uVkCompute` and `sharerc` is the same, AKA 大神。

**Comment by antiagainst** [comment]
Yes, if you'd like to run `glslc` on Jetson _itself_, you need an ARM build of it. Try to see if Android NDK has it, as the CMake will also try to find under [ANDROID_NDK](https://github.com/google/uVkCompute/blob/main/cmake/uvkc_find_vulkan_toolchain.cmake#L32) path.

Another way is that you cross compile towards Jetson with a host machine, like the way Android is targeted. Then you can use the host `glslc`.

**Comment by antiagainst** [comment]
W.r.t. compilers, yeah right now only Clang is well tested. But only supporting Clang is not the intention; missing GCC support is a bug. If you are interested, pull requests to fix it would be awesome. Otherwise I can fix it later. :)

**Comment by tpoisonooo** [comment]
Ah, fix first bug in google/benchmark, please check~

**Comment by antiagainst** [comment]
Thanks for the fix! I think there are no further actionable items for this issue. So closing.
