### ISSUE TITLE
How to run this om Android devices?

### ISSUE THREAD

**Issue by SaschaWillems** [google/uVkCompute#20]
I have successfully build the project for Android and copied one benchmark over to a device, but when trying to run any of the benchmarks I get "permission denied". I tried with a Google Pixel 4a and a rooted Xiaomi Redmi 4X. Is there anything special required to have this run on Android?

**Comment by antiagainst** [comment]
Interesting. I have never encountered permission issues. What's the full error message there? Maybe missing `chmod +x` over the binary?

**Comment by SaschaWillems** [comment]
The `chmod +x` was the missing part. After applying that to one of the benchmarks I was able to run it on my Pixel 4a Thank you very much :)
